import { Question } from "../interfaces/Question";

export const englishTestQuestions: Question[] = [
    {
        description: "Question 1. Select correct word:",
        question: "I ____ from Ukraine.",
        options: ["Is", "Are", "Am", "Be"],
        answer: "Am",
        points: 1,
    },
    {
        description: "Question 2. Select correct article:",
        question: "My brother is _____ programmer.",
        options: ["The", "An", "A", "For"],
        answer: "A",
        points: 1,
    },
    {
        description: "Question 3. Select correct possessive pronoun:",
        question: "This is my friend. ____ name is Catherine.",
        options: ["Her", "She", "Our"],
        answer: "Her",
        points: 1,
    },
    {
        description: "Question 4. Select correct form of 'there to be':",
        question: "______ twenty-five desks in the class.",
        options: ["There is", "There are", "This is", "They are"],
        answer: "There are",
        points: 1,
    },
    {
        description: "Question 5. Select correct negative form:",
        question: "My mom _______ like horror films.",
        options: ["Does not", "No", "Is not", "Do not"],
        answer: "Does not",
        points: 1,
    },
    {
        description: "Question 6. Select correct verb form:",
        question: "I will call you later! I ___  right now.",
        options: ["`m sleeping", "Sleep", "Sleeping"],
        answer: "`m sleeping",
        points: 2,
    },
    {
        description: "Question 7. Select correct past form of 'to be':",
        question: "She _____  at the university last Tuesday.",
        options: ["Didn’t be", "Wasn’t", "Weren’t", "Isn’t"],
        answer: "Wasn’t",
        points: 2,
    },
    {
        description: "Question 8. Select correct form of offering:",
        question: "________ a piece of cake? No, thank you.",
        options: ["Do you like", "Would you like", "Want you", "Are you like"],
        answer: "Would you like",
        points: 2,
    },
    {
        description: "Question 9. Select correct comparative form:",
        question: "My room is ______ than yours.",
        options: ["More big", "Most big", "Bigger", "Biggest"],
        answer: "Bigger",
        points: 2,
    },
    {
        description: "Question 10. Select correct adverb for frequency:",
        question: "Vicky does not like sweets. She most likely ______ eats chocolate.",
        options: ["Rarely", "Sometimes", "Often", "Usually"],
        answer: "Rarely",
        points: 2,
    },
    {
        description: "Question 11. Select correct past continuous form:",
        question: "They ______ in the mall when it started to rain.",
        options: ["They walked", "Were walking", "Are walking", "Walk"],
        answer: "Were walking",
        points: 2,
    },
    {
        description: "Question 12. Select correct present perfect form:",
        question: "_____ ever been to Australia?",
        options: ["Have you", "Did you", "Do you", "Are you"],
        answer: "Have you",
        points: 2,
    },
    {
        description: "Question 13. Select correct time preposition:",
        question: "We have known each other ____ high school.",
        options: ["Since", "For", "From", "While"],
        answer: "Since",
        points: 2,
    },
    {
        description: "Question 14. Select correct modal verb:",
        question: "You _____ pay for the drinks. They are free.",
        options: ["Have to", "Don’t have to", "Don’t need to", "Doesn’t have to"],
        answer: "Don’t have to",
        points: 2,
    },
    {
        description: "Question 15. Select correct past ability modal:",
        question: "Ben was on vacation last week and he _____ come to your party.",
        options: ["Could not", "Can not", "Needn't", "Mustn't"],
        answer: "Could not",
        points: 3,
    },
    {
        description: "Question 16. Select correct conditional form:",
        question: "We'll stay at home if it ______ this afternoon.",
        options: ["Raining", "Rains", "Will rain", "Rain"],
        answer: "Rains",
        points: 3,
    },
    {
        description: "Question 17. Select correct superlative form:",
        question: "John is ______ player in this team.",
        options: ["The best", "Most better", "Better than", "Best than"],
        answer: "The best",
        points: 1,
    },
    {
        description: "Question 18. Select correct passive form:",
        question: "Paris ______  by hundreds of thousands of tourists every year.",
        options: ["Is visited", "Visiting", "Visits"],
        answer: "Is visited",
        points: 2,
    },
    {
        description: "Question 19. Select correct response:",
        question: "I do not like orange juice very much. _______.",
        options: ["Neither do I", "I do not too", "I am not too"],
        answer: "Neither do I",
        points: 3,
    },
    {
        description: "Question 20. Select correct transportation method:",
        question: "I _____ bus on Mondays.",
        options: ["`m going to work with", "`m going to work by", "Go to work with", "Go to work by"],
        answer: "Go to work by",
        points: 3,
    },
    {
        description: "Question 21. Select correct preposition:",
        question: "I don't want to see her ____ the party tonight.",
        options: ["At", "On", "In"],
        answer: "At",
        points: 1,
    },
    {
        description: "Question 22. Select correct conjunction:",
        question: "I wasn't hungry, ___ I didn't eat.",
        options: ["So", "Because", "But", "And"],
        answer: "So",
        points: 1,
    },
    {
        description: "Question 23. Select correct indefinite pronoun:",
        question: "Can I stay here tonight? I have  _____  to go.",
        options: ["Nowhere", "Anywhere", "Somewhere"],
        answer: "Nowhere",
        points: 2,
    },
    {
        description: "Question 24. Select correct past subjunctive form:",
        question: "I wouldn't drink that milk if I ___  you.",
        options: ["Were", "`d be", "Was"],
        answer: "Were",
        points: 3,
    },
    {
        description: "Question 25. Select correct past habit form:",
        question: "I ____ work in a bank, but now I'm working as a designer.",
        options: ["Used to", "Got used to", "Was used to"],
        answer: "Used to",
        points: 3,
    },
    {
        description: "Question 26. Select correct conjunction:",
        question: "Don't call the police  ____ it's strictly necessary.",
        options: ["Unless", "Whether or not", "Even if"],
        answer: "Unless",
        points: 2,
    },
    {
        description: "Question 27. Select correct preposition:",
        question: "I was keen _____ learning languages when I was at college.",
        options: ["On", "At", "About", "In"],
        answer: "On",
        points: 2,
    },
    {
        description: "Question 28. Select correct preposition:",
        question: "Matthew is fond ____ reading and visits the library every week.",
        options: ["Of", "Doing", "About", "Going"],
        answer: "Of",
        points: 2,
    },
    {
        description: "Question 29. Select correct verb:",
        question: "I’m thinking about _____ chemistry next year because I’m finding it very boring.",
        options: ["Dropping", "Enrolling", "Failing", "Sitting"],
        answer: "Dropping",
        points: 2,
    },
    {
        description: "Question 30. Select correct adjective phrase:",
        question: "I'd prefer to stay somewhere _____ than in a touristy area.",
        options: ["Exotic", "Vibrant", "Overrated", "Off the beaten track"],
        answer: "Off the beaten track",
        points: 2,
    },
    {
        description: "Question 31. Select correct noun:",
        question: "I always feel anxious before giving a _____.",
        options: ["Presentation", "Essay", "Exam", "Research"],
        answer: "Presentation",
        points: 1,
    },
    {
        description: "Question 32. Select correct verb:",
        question: "Only two people _____ for the position, so we didn’t have to do a lot of interviews.",
        options: ["Applied", "Resigned", "Quit", "Retired"],
        answer: "Applied",
        points: 2,
    },
    {
        description: "Question 33. Select correct phrasal verb:",
        question: "You may not like the cold weather here, but you’ll have to_____, I’m afraid.",
        options: ["Tell it off", "Put up with it", "Put it off", "Sort it off"],
        answer: "Put up with it",
        points: 3,
    },
    {
        description: "Question 34. Select correct verb:",
        question: "They say that the diamond _____ over €5 million.",
        options: ["Is worth", "Pays", "Can afford", "Borrows"],
        answer: "Is worth",
        points: 2,
    },
    {
        description: "Question 35. Select correct phrasal verb:",
        question: "It’s a good idea to _____ these files in case your computer crashes.",
        options: ["Back up", "Upgrade", "Sign up", "Browse"],
        answer: "Back up",
        points: 1,
    },
    {
        description: "Question 36. Select correct noun:",
        question: "The doctor was tired because he’d just finished a 12-hour _____.",
        options: ["Bonus", "Leave", "Shift", "Apprenticeship"],
        answer: "Shift",
        points: 2,
    },
    {
        description: "Question 37. Select correct concern:",
        question: "With robots replacing many jobs these days, lots of people worry about _____.",
        options: ["Being sacked", "Being made redundant", "Getting promoted", "Meeting deadlines"],
        answer: "Being made redundant",
        points: 3,
    },
    {
        description: "Question 38. Select correct noun:",
        question: "I did a short _____ at a veterinary clinic last summer.",
        options: ["Qualification", "Undergraduate", "Internship", "Project work"],
        answer: "Internship",
        points: 2,
    },
    {
        description: "Question 39. Select correct financial term:",
        question: "The ______ on my mortgage has risen in the past year.",
        options: ["Interest rate", "Budget", "Income", "Expense"],
        answer: "Interest rate",
        points: 2,
    },
    {
        description: "Question 40. Select correct adjective:",
        question: "Although the rest of the family had strong opinions about the matter, Maud felt quite _____.",
        options: ["Calm", "Indifferent", "Hysterical", "Relieved"],
        answer: "Indifferent",
        points: 2,
    },
    {
        description: "Question 41. Select correct verb phrase:",
        question:
            "To combat climate change, industries are being urged to _____ emissions to help reduce the impact of global warming.",
        options: ["Cut back on", "Tackle", "Dump", "Break down"],
        answer: "Cut back on",
        points: 3,
    },
    {
        description: "Question 42. Reading comprehension:",
        question: "Why did John go to the store?",
        options: ["To buy oranges.", "To buy apples.", "To make an apple pie.", "Because he was disappointed."],
        answer: "To buy apples.",
        points: 1,
    },
    {
        description: "Question 43. Reading comprehension:",
        question: "How did Martin’s perception of New York change over time?",
        options: [
            "He found it overwhelming initially and now finds it boring.",
            "He first found it overwhelming, but now enjoys the city.",
            "He did not like the diverse culture initially.",
            "He still finds the city overwhelming.",
        ],
        answer: "He first found it overwhelming, but now enjoys the city.",
        points: 2,
    },
    {
        description: "Read the text and answer the follow questions:",
        question:
            "Six out of ten CV’s which are prepared by Information Technology professionals fail to meet the basic standards and are turned down without even being read fully, according to a recruitment company. As a consequence, thousands of candidates are excluding themselves from attractive job opportunities. Although the company handles over 60,000 CV’s per year, it estimates that at least 60% would not be admitted if they were sent directly to potential clients due to basic errors.\n" +
            "The company Marketing Director said, “Sadly it’s often the most highly qualified candidates whose CV’s are so poorly constructed that they are literally dead on arrival. Attractive job opportunities in the IT industry often generate intense competition and there is often little to choose between the candidates”.\n" +
            "“Advice on the presentation format of CV’s in relation to the requirements that they are being submitted for should be an Industry standard so as to add real value to the candidates that you are representing and indeed to fulfil your professional obligations to your clients”.\n" +
            "“Writing a CV can be extremely difficult and too often a CV turns out to be a generic overview including a lot of information that is irrelevant. People should remember that an employer typically spends between 15 and 30 seconds scanning each CV and you have that one chance to make an impression”.\n" +
            "“A good CV is more than just documentation of your career path; it is a marketing tool designed to present your professional career experience according to the new job specification. It should also include details of past professional successes that effectively demonstrate your ability to undertake the job responsibilities outlined”.\n",
        options: [],
        answer: "",
        points: 0,
    },
    {
        description: "Question 44. Reading comprehension:",
        question: "According to the text, what is the role of education in societal development?",
        options: [
            "Education is the sole driving force of societal development.",
            "Education has no role in societal development.",
            "Education is an integral part, but not the only factor driving societal development.",
            "The role of education in societal development is entirely misunderstood.",
        ],
        answer: "Education is an integral part, but not the only factor driving societal development.",
        points: 3,
    },
    {
        description: "Question 45. Reading comprehension:",
        question: "Recruitment companies say that potential clients ...",
        options: ["Make basic mistakes", "Only get 60% of CV`s", "Reject Cv`s with mistakes"],
        answer: "Reject Cv`s with mistakes",
        points: 1,
    },
    {
        description: "Question 46. Reading comprehension:",
        question: "The Marketing Director said that the best candidates ...",
        options: ["Are the most affected", "Do not send CV`s", "Write the best CV`s"],
        answer: "Are the most affected",
        points: 1,
    },
    {
        description: "Question 47. Reading comprehension:",
        question: "The Marketing Director suggests that candidates ought to pay attention to ...",
        options: ["CV`s presentation", "Other companies", "Other competitors"],
        answer: "CV`s presentation",
        points: 1,
    },
    {
        description: "Question 48. Reading comprehension:",
        question: "The Marketing Director says that very often CV’s include ...",
        options: ["Necessary details", "Unimportant information", "Very little information"],
        answer: "Unimportant information",
        points: 2,
    },
    {
        description: "Question 49. Reading comprehension:",
        question: "Candidates should remember that employers ...",
        options: ["Are typical people", "Are very busy people", "Make an impression on people"],
        answer: "Are very busy people",
        points: 1,
    },
    {
        description: "Question 50. Reading comprehension:",
        question: "A good curriculum should represent ...",
        options: ["The new job specification", "Your marketing tools", "Your overall skills"],
        answer: "Your overall skills",
        points: 2,
    },
];
