const namesDE = [
    "Alexander",
    "Johannes",
    "Marie",
    "Sophie",
    "Paul",
    "Emma",
    "Maximilian",
    "Hannah",
    "Leon",
    "Lena",
    "Lukas",
    "Mia",
    "Ben",
    "Anna",
    "Finn",
    "Lea",
    "Elias",
    "Laura",
    "Noah",
    "Sarah",
    "Julian",
    "Emily",
    "Felix",
    "Lina",
    "Tim",
    "Lisa",
    "Jonas",
    "Amelie",
    "Philipp",
    "Sophia",
    "David",
    "Julia",
    "Nico",
    "Luisa",
    "Tom",
    "Maja",
    "Fabian",
    "Mila",
    "Tobias",
    "Nina",
    "Simon",
    "Lilly",
    "Matthias",
    "Charlotte",
    "Oliver",
    "Clara",
    "Daniel",
    "Marlene",
    "Sebastian",
    "Greta",
];

const placesDE = [
    "Berge",
    "Kino",
    "Konzertsaal",
    "Wald",
    "Zoo",
    "Fitnessstudio",
    "Stadion",
    "Kirche",
    "Tempel",
    "Moschee",
    "Bauernhof",
    "Freizeitpark",
    "See",
    "Fluss",
    "Flughafen",
    "Bahnhof",
    "Bushaltestelle",
    "Universität",
    "Hotel",
    "Krankenhaus",
    "Apotheke",
    "Bäckerei",
    "Garten",
    "Park",
    "Brücke",
    "Schloss",
    "Höhle",
    "Wüste",
    "Palast",
    "Straße",
    "Haus",
    "Boot",
    "Kreuzfahrt",
    "Resort",
    "Kantine",
    "Wasserpark",
    "Fußballfeld",
    "Restaurant",
    "McDonald's",
    "Café",
    "Dorf",
    "Berlin",
    "München",
    "Hamburg",
    "Frankfurt",
    "Köln",
    "Stuttgart",
    "Düsseldorf",
    "Dresden",
    "Leipzig",
    "Nürnberg",
];

const actionsDE = [
    "spazieren gehen",
    "fernsehen",
    "aufräumen",
    "Musik hören",
    "Bilder malen",
    "Pflanzen pflanzen",
    "telefonieren",
    "Hausaufgaben machen",
    "meditieren",
    "tanzen",
    "Abendessen kochen",
    "fotografieren",
    "ein Gedicht schreiben",
    "den Hund zeichnen",
    "singen",
    "ein Instrument spielen",
    "Brot backen",
    "Videospiele spielen",
    "der Mutter helfen",
    "einen Spaziergang machen",
    "schwimmen",
    "Freunde treffen",
    "in die Berge gehen",
    "Tiere füttern",
    "Brettspiele spielen",
    "ein Konzert besuchen",
    "an einem Kurs teilnehmen",
    "Yoga üben",
    "einen Film schauen",
    "Puzzles zusammensetzen",
    "Vögel beobachten",
    "eine Wanderung planen",
    "ein Picknick machen",
    "Fahrrad fahren",
    "eine Skulptur machen",
    "Skizzen zeichnen",
    "zum Mittagessen ausgehen",
    "mit dem Zug fahren",
    "ein Zelt aufstellen",
    "angeln",
    "im Meer schwimmen",
    "sich auf einen Marathon vorbereiten",
    "reiten",
    "surfen lernen",
    "Gitarre spielen",
    "Schlittschuh laufen",
    "Borschtsch kochen",
    "einen Computer reparieren",
    "das Auto waschen",
];

export const getRandomTopicDE = () => {
    const name = namesDE[Math.floor(Math.random() * namesDE.length)];
    const action = actionsDE[Math.floor(Math.random() * actionsDE.length)];
    const place = placesDE[Math.floor(Math.random() * placesDE.length)];

    return `${name} ${action} at ${place}.`;
};

const hardTopicsDE = [
    "Makroökonomie",
    "Mikroökonomie",
    "Internationale Beziehungen",
    "Politische Theorie",
    "Kognitive Psychologie",
    "Verhaltensökonomie",
    "Astrophysik",
    "Genetik",
    "Molekularbiologie",
    "Künstliche Intelligenz",
    "Maschinelles Lernen",
    "Datenwissenschaft",
    "Ethik der Technologie",
    "Philosophie des Geistes",
    "Neurowissenschaften",
    "Soziologie der Religion",
    "Kulturelle Anthropologie",
    "Wirtschaftspolitik",
    "Ökologische Nachhaltigkeit",
    "Stadtplanung",
    "Demographische Studien",
    "Medienwissenschaft",
    "Kommunikationstheorie",
    "Globalisierung",
    "Soziale Gerechtigkeit",
    "Menschenrechte",
    "Umweltrecht",
    "Gesundheitsökonomie",
    "Bioethik",
    "Archäologie",
    "Klimawandel",
    "Nachhaltige Entwicklung",
    "Weltliteratur",
    "Postkoloniale Studien",
    "Gender Studies",
    "Rassismus und Ethnizität",
    "Migrationsstudien",
    "Erziehungsphilosophie",
    "Sprachentwicklung",
    "Semantik und Pragmatik",
    "Computerlinguistik",
    "Algorithmusdesign",
    "Cyber-Sicherheit",
    "Finanzmathematik",
    "Wirtschaftsingenieurwesen",
    "Operations Research",
    "Energietechnik",
    "Robotik",
    "Materialwissenschaft",
    "Nanotechnologie",
    "Bionik",
    "Medizintechnik",
    "Pharmakologie",
    "Klinische Psychologie",
    "Forensische Psychologie",
    "Verkehrswesen",
    "Logistikmanagement",
    "Versicherungswirtschaft",
    "Verhaltensmedizin",
    "Ernährungswissenschaft",
    "Sportwissenschaft",
    "Musikwissenschaft",
    "Filmtheorie",
    "Theaterwissenschaft",
    "Kunstgeschichte",
    "Moderne Kunst",
    "Religionswissenschaft",
    "Mittelalterliche Geschichte",
    "Renaissance-Studien",
    "Zeitgenössische Geschichte",
    "Wirtschaftsgeschichte",
    "Literaturtheorie",
    "Kreatives Schreiben",
    "Dramaturgie",
    "Pädagogik",
    "Didaktik",
    "Lerntechnologien",
    "Internationale Entwicklung",
    "Friedens- und Konfliktforschung",
    "Diplomatie",
    "Geopolitik",
    "Verhaltensökologie",
    "Evolutionsbiologie",
    "Systembiologie",
    "Theoretische Informatik",
    "Numerische Mathematik",
    "Stochastik",
    "Statistische Physik",
    "Theoretische Chemie",
    "Biophysik",
    "Mikrobiologie",
    "Virologie",
    "Immunologie",
    "Pflanzenwissenschaften",
    "Tierverhalten",
    "Entwicklungspsychologie",
    "Wirtschaftsinformatik",
    "Digitale Transformation",
    "Unternehmensstrategie",
    "Innovationsmanagement",
];

export const getRandomHardTopicDE = () => {
    return hardTopicsDE[Math.floor(Math.random() * hardTopicsDE.length)];
};
