const namesDE = [
    "Alexander",
    "Johannes",
    "Marie",
    "Sophie",
    "Paul",
    "Emma",
    "Maximilian",
    "Hannah",
    "Leon",
    "Lena",
    "Lukas",
    "Mia",
    "Ben",
    "Anna",
    "Finn",
    "Lea",
    "Elias",
    "Laura",
    "Noah",
    "Sarah",
    "Julian",
    "Emily",
    "Felix",
    "Lina",
    "Tim",
    "Lisa",
    "Jonas",
    "Amelie",
    "Philipp",
    "Sophia",
    "David",
    "Julia",
    "Nico",
    "Luisa",
    "Tom",
    "Maja",
    "Fabian",
    "Mila",
    "Tobias",
    "Nina",
    "Simon",
    "Lilly",
    "Matthias",
    "Charlotte",
    "Oliver",
    "Clara",
    "Daniel",
    "Marlene",
    "Sebastian",
    "Greta",
];

const placesDE = [
    "Berge",
    "Kino",
    "Konzertsaal",
    "Wald",
    "Zoo",
    "Fitnessstudio",
    "Stadion",
    "Kirche",
    "Tempel",
    "Moschee",
    "Bauernhof",
    "Freizeitpark",
    "See",
    "Fluss",
    "Flughafen",
    "Bahnhof",
    "Bushaltestelle",
    "Universität",
    "Hotel",
    "Krankenhaus",
    "Apotheke",
    "Bäckerei",
    "Garten",
    "Park",
    "Brücke",
    "Schloss",
    "Höhle",
    "Wüste",
    "Palast",
    "Straße",
    "Haus",
    "Boot",
    "Kreuzfahrt",
    "Resort",
    "Kantine",
    "Wasserpark",
    "Fußballfeld",
    "Restaurant",
    "McDonald's",
    "Café",
    "Dorf",
    "Berlin",
    "München",
    "Hamburg",
    "Frankfurt",
    "Köln",
    "Stuttgart",
    "Düsseldorf",
    "Dresden",
    "Leipzig",
    "Nürnberg",
];

const actionsDE = [
    "spazieren gehen",
    "fernsehen",
    "aufräumen",
    "Musik hören",
    "Bilder malen",
    "Pflanzen pflanzen",
    "telefonieren",
    "Hausaufgaben machen",
    "meditieren",
    "tanzen",
    "Abendessen kochen",
    "fotografieren",
    "ein Gedicht schreiben",
    "den Hund zeichnen",
    "singen",
    "ein Instrument spielen",
    "Brot backen",
    "Videospiele spielen",
    "der Mutter helfen",
    "einen Spaziergang machen",
    "schwimmen",
    "Freunde treffen",
    "in die Berge gehen",
    "Tiere füttern",
    "Brettspiele spielen",
    "ein Konzert besuchen",
    "an einem Kurs teilnehmen",
    "Yoga üben",
    "einen Film schauen",
    "Puzzles zusammensetzen",
    "Vögel beobachten",
    "eine Wanderung planen",
    "ein Picknick machen",
    "Fahrrad fahren",
    "eine Skulptur machen",
    "Skizzen zeichnen",
    "zum Mittagessen ausgehen",
    "mit dem Zug fahren",
    "ein Zelt aufstellen",
    "angeln",
    "im Meer schwimmen",
    "sich auf einen Marathon vorbereiten",
    "reiten",
    "surfen lernen",
    "Gitarre spielen",
    "Schlittschuh laufen",
    "Borschtsch kochen",
    "einen Computer reparieren",
    "das Auto waschen",
];

export const getRandomTopicDE = () => {
    const name = namesDE[Math.floor(Math.random() * namesDE.length)];
    const action = actionsDE[Math.floor(Math.random() * actionsDE.length)];
    const place = placesDE[Math.floor(Math.random() * placesDE.length)];

    return `${name} ${action} ${place}.`;
};

const hardTopicsDE = [
    "Klimawandel und seine Auswirkungen auf die Umwelt",
    "Der Aufstieg der künstlichen Intelligenz und seine Implikationen",
    "Globale wirtschaftliche Ungleichheit und Armut",
    "Ethische Dilemmas in der modernen Gesellschaft",
    "Die Flüchtlingskrise und ihre humanitären Auswirkungen",
    "Bedrohungen der Cybersicherheit und Datenschutzprobleme im Internet",
    "Die Zukunft der Arbeit im Zeitalter der Automatisierung",
    "Bewusstsein für psychische Gesundheit und Abbau von Stigmatisierung",
    "Nachhaltige Lebenspraktiken und erneuerbare Energiequellen",
    "Die Rolle der Technologie in der Bildung",
    "Kulturelle Aneignung und ihre Auswirkungen auf marginalisierte Gemeinschaften",
    "Die Bedeutung von bürgerschaftlichem Engagement und Aktivismus",
    "Urbanisierung und ihre Auswirkungen auf Gemeinschaften und die Umwelt",
    "Die Ethik der Gentechnik und Biotechnologie",
    "Geschlechtergleichstellung und Frauenthemen",
    "Rechte indigener Völker und Bemühungen zum Landesschutz",
    "Die Auswirkungen sozialer Medien auf Gesellschaft und psychische Gesundheit",
    "Globale Gesundheitsherausforderungen und Pandemievorsorge",
    "Der Schnittpunkt von Religion und Politik",
    "Umweltschutzbemühungen und der Schutz gefährdeter Arten",
    "Zugang zu Bildung für benachteiligte Gemeinschaften",
    "Die Auswirkungen des Massentourismus auf lokale Kulturen und Wirtschaften",
    "Ernährungssicherheit und nachhaltige Landwirtschaftspraktiken",
    "Die Rolle von NGOs und internationalen Hilfsorganisationen",
    "Technologische Fortschritte in der Medizin und Gesundheitsversorgung",
    "Die Zukunft des Transports und der urbanen Mobilität",
    "Systeme und Ressourcen zur Unterstützung der psychischen Gesundheit",
    "Wildtierschutz und Erhaltung von Lebensräumen",
    "Die Ethik von Tierversuchen und Produkten ohne Tierquälerei",
    "Bewegungen für soziale Gerechtigkeit und systemische Diskriminierung",
    "Raumfahrt und die Suche nach außerirdischem Leben",
    "Politik und Initiativen für erneuerbare Energien",
    "Die Auswirkungen der Globalisierung auf die kulturelle Vielfalt",
    "Die Zukunft der Demokratie und politische Beteiligung",
    "Nachhaltige Mode und ethischer Konsum",
    "Zugang zu sauberem Wasser und sanitären Einrichtungen weltweit",
    "LGBTQ+ Rechte und Inklusivität in der Gesellschaft",
    "Die Rolle von Kunst und Kultur in der gesellschaftlichen Entwicklung",
    "Prävention von Cybermobbing und Online-Belästigung",
    "Herausforderungen der psychischen Gesundheit bei Jugendlichen",
    "Umweltaktivismus und Basisbewegungen",
    "Die Zukunft der künstlichen Intelligenz und Ethik in der Technologie",
    "Strategien zur Armutsbekämpfung und wirtschaftliche Entwicklung",
    "Menschenhandel und moderne Sklaverei",
    "Zugang zur Gesundheitsversorgung in Entwicklungsländern",
    "Die Auswirkungen der Automatisierung auf den Arbeitsplatzverlust",
    "Resilienz der Gemeinschaften angesichts von Naturkatastrophen",
    "Religiöser Extremismus und seine Auswirkungen auf die globale Sicherheit",
    "Die Psychologie der Entscheidungsfindung und Verhaltensänderung",
];

export const getRandomHardTopicDE = () => {
    return hardTopicsDE[Math.floor(Math.random() * hardTopicsDE.length)];
};
