const namesEN = [
    "Muhammad",
    "Sofia",
    "Kai",
    "Chihiro",
    "Diego",
    "Fatima",
    "Ivan",
    "Aisha",
    "Hugo",
    "Mei",
    "Amir",
    "Leila",
    "Luca",
    "Maya",
    "Rafael",
    "Zara",
    "Hiroshi",
    "Isla",
    "Andrei",
    "Freya",
    "Jamal",
    "Ingrid",
    "Dimitri",
    "Nala",
    "Pedro",
    "Layla",
    "Lars",
    "Priya",
    "Alejandro",
    "Anouk",
    "Ali",
    "Selena",
    "Emil",
    "Amara",
    "Luca",
    "Sienna",
    "Nikolai",
    "Yara",
    "Adil",
    "Alina",
    "Miguel",
    "Anya",
    "Matteo",
    "Luna",
    "Hassan",
    "Amara",
    "Stefan",
    "Astrid",
    "Jamal",
    "Kiara",
];

const actionsEN = [
    "walks",
    "watches TV",
    "cleans",
    "listens to music",
    "paints",
    "gardens",
    "talks on the phone",
    "exercises",
    "meditates",
    "dances",
    "takes a nap",
    "photographs",
    "writes",
    "draws",
    "sings",
    "plays an instrument",
    "bakes",
    "plays video games",
    "volunteers",
    "goes for a drive",
    "swims",
    "meets friends",
    "goes hiking",
    "feeds pets",
    "plays board games",
    "attends a concert",
    "attends a class",
    "practices yoga",
    "watches a movie",
    "completes puzzles",
    "birdwatches",
    "camping",
    "picnics",
    "biking",
    "sculpting",
    "sketching",
    "dining out",
    "barbecuing",
    "camping",
    "fishing",
    "kayaking",
    "rafting",
    "horseback riding",
    "surfing",
    "rock climbing",
    "ice skating",
    "skiing",
    "snowboarding",
    "sledding",
];

const placesEN = [
    "the mountains",
    "a movie theater",
    "a concert hall",
    "a forest",
    "a zoo",
    "a gym",
    "a stadium",
    "a church",
    "a temple",
    "a mosque",
    "a farm",
    "an amusement park",
    "a lake",
    "a river",
    "an airport",
    "a train station",
    "a bus stop",
    "a campsite",
    "a hotel",
    "a hospital",
    "a pharmacy",
    "a bakery",
    "a farm",
    "a garden",
    "a rooftop",
    "a bridge",
    "a castle",
    "a cave",
    "a desert",
    "a mansion",
    "a palace",
    "a skyscraper",
    "a submarine",
    "a spaceship",
    "a volcano",
    "an iceberg",
    "a waterfall",
    "an island",
    "a space station",
    "a submarine",
    "a ghost town",
    "a village",
    "a city square",
    "a temple",
    "a pyramid",
    "a lighthouse",
    "a beach house",
    "a cottage",
    "a mansion",
];

export const getRandomTopicDE = () => {
    const name = namesEN[Math.floor(Math.random() * namesEN.length)];
    const action = actionsEN[Math.floor(Math.random() * actionsEN.length)];
    const place = placesEN[Math.floor(Math.random() * placesEN.length)];

    return `${name} ${action} at ${place}.`;
};

const hardTopicsEN = [
    "Macroeconomics",
    "Microeconomics",
    "International Relations",
    "Political Theory",
    "Cognitive Psychology",
    "Behavioral Economics",
    "Astrophysics",
    "Genetics",
    "Molecular Biology",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Ethics of Technology",
    "Philosophy of Mind",
    "Neuroscience",
    "Sociology of Religion",
    "Cultural Anthropology",
    "Economic Policy",
    "Ecological Sustainability",
    "Urban Planning",
    "Demographic Studies",
    "Media Studies",
    "Communication Theory",
    "Globalization",
    "Social Justice",
    "Human Rights",
    "Environmental Law",
    "Health Economics",
    "Bioethics",
    "Archaeology",
    "Climate Change",
    "Sustainable Development",
    "World Literature",
    "Postcolonial Studies",
    "Gender Studies",
    "Racism and Ethnicity",
    "Migration Studies",
    "Philosophy of Education",
    "Language Development",
    "Semantics and Pragmatics",
    "Computational Linguistics",
    "Algorithm Design",
    "Cybersecurity",
    "Financial Mathematics",
    "Industrial Engineering",
    "Operations Research",
    "Energy Engineering",
    "Robotics",
    "Materials Science",
    "Nanotechnology",
    "Bionics",
    "Medical Technology",
    "Pharmacology",
    "Clinical Psychology",
    "Forensic Psychology",
    "Transportation Engineering",
    "Logistics Management",
    "Insurance Economics",
    "Behavioral Medicine",
    "Nutritional Science",
    "Sports Science",
    "Musicology",
    "Film Theory",
    "Theater Studies",
    "Art History",
    "Modern Art",
    "Religious Studies",
    "Medieval History",
    "Renaissance Studies",
    "Contemporary History",
    "Economic History",
    "Literary Theory",
    "Creative Writing",
    "Dramaturgy",
    "Pedagogy",
    "Didactics",
    "Learning Technologies",
    "International Development",
    "Peace and Conflict Studies",
    "Diplomacy",
    "Geopolitics",
    "Behavioral Ecology",
    "Evolutionary Biology",
    "Systems Biology",
    "Theoretical Computer Science",
    "Numerical Mathematics",
    "Stochastics",
    "Statistical Physics",
    "Theoretical Chemistry",
    "Biophysics",
    "Microbiology",
    "Virology",
    "Immunology",
    "Plant Sciences",
    "Animal Behavior",
    "Developmental Psychology",
    "Business Informatics",
    "Digital Transformation",
    "Corporate Strategy",
    "Innovation Management",
];

export const getRandomHardTopicEN = () => {
    return hardTopicsEN[Math.floor(Math.random() * hardTopicsEN.length)];
};
