import { Spinner } from "flowbite-react";
import SideBar from "../components/layout/SideBar";
import { useUser } from "../context/UserContext";
import React from "react";
import { getFunctions, httpsCallable } from "firebase/functions";
import { AnswerReviewRequest, DescriptionData, GrammarQuestionRequest } from "../interfaces/AiRequests";
import ExerciseWrapper from "../components/layout/ExerciseWrapper";

const descriptionData: DescriptionData = {
    mainHeading: "Let's Practice Grammar!",
    smallDescription:
        "Whether you are a beginner or an advanced learner, we have something for everyone. You'll receive grammar exercises tailored to your proficiency level, with intentional errors to identify and correct.",
    paragraphs: [
        "For beginners, you'll receive simpler sentences and words to help build your foundational skills. Advanced learners will get more complex texts designed to challenge and enhance your grammatical understanding.",
        "Each task is generated by ChatGPT, providing you with unique and engaging sentences or texts that contain intentional errors. Your goal is to identify these errors and provide the corrected version.",
        "Submit your answers to receive a comprehensive review of what you did correctly and areas where you can improve. Detailed feedback will be provided to help you understand the right and wrong aspects of your corrections.",
        "We wish you good luck and lots of fun on your journey to mastering grammar!",
    ],
    taskDescription: "Task is to find grammar mistakes and correct them.",
};

const Grammar = () => {
    const { userData, setUserData } = useUser();

    const functions = getFunctions();
    const getGrammarQuestion = httpsCallable<GrammarQuestionRequest, string>(functions, "getGrammarQuestion");
    const checkGrammarAnswer = httpsCallable<AnswerReviewRequest, string>(functions, "checkGrammarAnswer");

    if (!userData) {
        return (
            <div className="flex items-center justify-center h-full" style={{ minHeight: "80vh" }}>
                <Spinner className="h-24 w-24" />
            </div>
        );
    }

    return (
        <SideBar>
            <ExerciseWrapper
                pageType="grammar"
                userData={userData}
                setUserData={setUserData}
                generateQuestion={getGrammarQuestion}
                generateAnswerReview={checkGrammarAnswer}
                descriptionData={descriptionData}
            />
        </SideBar>
    );
};

export default Grammar;
